# Generated by Django 2.1 on 2018-08-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=20)),
                ('spanish', models.CharField(max_length=20)),
                ('sentence', models.CharField(max_length=100)),
            ],
        ),
    ]
